server:
  port: 5000
spring:
  application:
    name: stockmanager
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR_ADMIN
#  datasource:
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#    hikari:
#      maximum-pool-size: 10
#      jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#      username: sa
#      password: sa
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration,classpath:db/specific/{vendor}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        ddl-auto: validate

# hikari; https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-configure-a-datasource
app:
  datasource:
    jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

#logging:
#  file: app.log